DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 60001
DEFAULT_POINTS = 10000
DEFAULT_Y_MAX = 16384.0
DEFAULT_DATA_FORMAT = "sensor_frame"

SOCKET_RECV_BUFFER_SIZE_BYTES = 8192
RECONNECT_INTERVAL_SECONDS = 2.0
TIMER_INTERVAL_SECONDS = 0.01

BUFFER_HISTORY_FACTOR = 30
INITIALIZATION_FRAMES_COUNT = 3

STATUS_INITIALIZING_TEXT = "Initializing..."
WINDOW_TITLE = "RTT Channel Monitor"
HELP_HINT_TEXT = "Press H for help"
