include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/midismith_require_lib.cmake)

macro(midismith_add_lib)
    cmake_parse_arguments(_MSLIB "" "NAME" "SOURCES;DEPENDS;LINK_LIBRARIES" ${ARGN})

    # Resolve midismith dependencies (require + link).
    set(_MSLIB_ALL_LINK_LIBS "")
    if(_MSLIB_DEPENDS)
        foreach(_dep ${_MSLIB_DEPENDS})
            midismith_require_lib(${_dep})
            string(REPLACE "-" "_" _dep_target "${_dep}")
            list(APPEND _MSLIB_ALL_LINK_LIBS ${_dep_target})
        endforeach()
        unset(_dep)
        unset(_dep_target)
    endif()
    if(_MSLIB_LINK_LIBRARIES)
        list(APPEND _MSLIB_ALL_LINK_LIBS ${_MSLIB_LINK_LIBRARIES})
    endif()

    if(_MSLIB_SOURCES)
        add_library(${_MSLIB_NAME} STATIC)
        target_compile_features(${_MSLIB_NAME} PUBLIC cxx_std_20)
        target_include_directories(${_MSLIB_NAME} PUBLIC include)
        target_sources(${_MSLIB_NAME} PRIVATE ${_MSLIB_SOURCES})
        if(_MSLIB_ALL_LINK_LIBS)
            target_link_libraries(${_MSLIB_NAME} PUBLIC ${_MSLIB_ALL_LINK_LIBS})
        endif()
    else()
        add_library(${_MSLIB_NAME} INTERFACE)
        target_compile_features(${_MSLIB_NAME} INTERFACE cxx_std_20)
        target_include_directories(${_MSLIB_NAME} INTERFACE include)
        if(_MSLIB_ALL_LINK_LIBS)
            target_link_libraries(${_MSLIB_NAME} INTERFACE ${_MSLIB_ALL_LINK_LIBS})
        endif()
    endif()

    if(HOST_TESTS)
        enable_testing()
        if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/tests/CMakeLists.txt")
            add_subdirectory(tests)
        endif()
    endif()

    unset(_MSLIB_NAME)
    unset(_MSLIB_SOURCES)
    unset(_MSLIB_DEPENDS)
    unset(_MSLIB_LINK_LIBRARIES)
    unset(_MSLIB_ALL_LINK_LIBS)
    unset(_MSLIB_UNPARSED_ARGUMENTS)
    unset(_MSLIB_KEYWORDS_MISSING_VALUES)
endmacro()
